### ISSUE TITLE
Language issue with cancellations

### ISSUE THREAD

**Issue by ferhado** [ready2order/r2o-api-client-php#7]
We´re having an issue with cancelled invoices. The language setting in our account usually is German however when we cancel invoices the language switches to English. How can I set the language in the cancelled invoice to German?

Here is my example code:

     r2o_api->post(
		"document/invoice/{$r2o_id}/delete",
		array(
		  "id" => $r2o_id,
		  "storno_id" => $storno_id,
		  "storno_reason" => "Korrektur",
		  "invoice_externalReferenceNumber" => $invoice_nr
		)
	  );

**Comment by duxthefux** [comment]
The pull request https://github.com/ready2order/r2o-api-client-php/pull/8 introduces a `Client::setLanguage()`-method which can be used to set the `Accept-Language` header.
